-- Base query for Metabase model "branch_monthly_kpi_base".
-- This now reads from curated semantic artifacts generated by:
-- make semantic-build
-- Source contract: bi/semantic/contract.yml

select
    month_start_date,
    branch_id,
    total_loan_disbursement_amount,
    total_repayment_amount,
    total_active_policies,
    total_number_of_loans,
    total_claim_amount,
    total_cross_sell_customers,
    repayment_coverage_ratio,
    claim_to_disbursement_ratio,
    avg_disbursement_per_loan,
    cross_sell_per_loan_ratio
from semantic.branch_monthly_kpi_base;
